#!/usr/bin/env bash
# modules/neovim.sh — Neovim + LazyVim setup

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/helpers.sh"
source "${SCRIPT_DIR}/config/packages.sh"

setup_neovim() {
  log_step "Neovim + LazyVim"

  local nvim_config="$HOME/.config/nvim"

  # Back up existing config
  if [[ -d "$nvim_config" ]] && [[ ! -L "$nvim_config" ]]; then
    if [[ -f "${nvim_config}/lazy-lock.json" ]]; then
      log_success "LazyVim already configured"
      return 0
    fi
    backup_if_exists "$nvim_config"
  fi

  if [[ -L "$nvim_config" ]]; then
    log_success "Neovim config already symlinked"
    return 0
  fi

  # Clone LazyVim starter
  log_info "Installing LazyVim starter..."
  git clone https://github.com/LazyVim/starter "$nvim_config"
  rm -rf "${nvim_config}/.git"

  # Enable language extras
  local extras_file="${nvim_config}/lua/config/lazy.lua"
  if [[ -f "$extras_file" ]]; then
    # Create extras spec file
    mkdir -p "${nvim_config}/lua/plugins"
    cat > "${nvim_config}/lua/plugins/extras.lua" << 'LUAEOF'
-- Auto-generated by mac-dev-setup
-- Language extras for Python, Go, Ruby, Docker
return {}
LUAEOF

    # LazyVim extras are enabled via lazyvim.json
    cat > "${nvim_config}/lazyvim.json" << 'JSONEOF'
{
  "extras": [
    "lazyvim.plugins.extras.lang.python",
    "lazyvim.plugins.extras.lang.go",
    "lazyvim.plugins.extras.lang.ruby",
    "lazyvim.plugins.extras.lang.docker"
  ],
  "news": {
    "NEWS.md": ""
  },
  "version": 7
}
JSONEOF

    log_success "LazyVim extras configured for Python, Go, Ruby, Docker"
  fi

  # Run neovim headless to install plugins
  log_info "Installing Neovim plugins (this may take a minute)..."
  nvim --headless "+Lazy! sync" +qa 2>/dev/null || true
  log_success "Neovim plugins installed"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup_neovim
fi
